# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('satellite-point-to-point-example', ['satellite-point-to-point'])
    obj.source = 'satellite-point-to-point-example.cc'

